=== XenoAmess/ArenaShooter/project/data/animations/animationDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT animation (trackEvent?,(trackD|trackT|trackVec2f|trackVec3f)*)>
<!ATTLIST animation length CDATA #REQUIRED>
<!ATTLIST animation loop (true|false) "false">

<!ELEMENT trackD (keyframeD+)>
<!ATTLIST trackD name ID #REQUIRED>
<!ELEMENT keyframeD EMPTY>
<!ATTLIST keyframeD time CDATA #REQUIRED>
<!ATTLIST keyframeD value CDATA #REQUIRED>

<!ELEMENT trackT (keyframeT+)>
<!ATTLIST trackT name ID #REQUIRED>
<!ELEMENT keyframeT EMPTY>
<!ATTLIST keyframeT time CDATA #REQUIRED>
<!ATTLIST keyframeT value CDATA #REQUIRED>

<!ELEMENT trackVec2f (keyframeVec2f+)>
<!ATTLIST trackVec2f name ID #REQUIRED>
<!ELEMENT keyframeVec2f EMPTY>
<!ATTLIST keyframeVec2f time CDATA #REQUIRED>
<!ATTLIST keyframeVec2f x CDATA #REQUIRED>
<!ATTLIST keyframeVec2f y CDATA #REQUIRED>

<!ELEMENT trackVec3f (keyframeVec3f+)>
<!ATTLIST trackVec3f name ID #REQUIRED>
<!ELEMENT keyframeVec3f EMPTY>
<!ATTLIST keyframeVec3f time CDATA #REQUIRED>
<!ATTLIST keyframeVec3f x CDATA #REQUIRED>
<!ATTLIST keyframeVec3f y CDATA #REQUIRED>
<!ATTLIST keyframeVec3f z CDATA #REQUIRED>

<!ELEMENT trackEvent EMPTY>
<!-- TODO -->

=== XenoAmess/ArenaShooter/project/data/animations/animTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE animation SYSTEM "animationDTD.dtd" >
<animation length="2.0" loop="true">
	
	<trackVec2f name="pos" interpolation="cubic">
		<keyframeVec2f time="0.0" x="0.0" y="0.0" />
		<keyframeVec2f time="0.5" x="200.0" y="0.0" />
		<keyframeVec2f time="1.0" x="200.0" y="200.0" />
		<keyframeVec2f time="1.5" x="0.0" y="200.0" />
		<keyframeVec2f time="2.0" x="0.0" y="0.0" />
	</trackVec2f>

	<trackD name="rot" interpolation="linear">
		<keyframeD time="0.0" value="0.0" />
	</trackD>

</animation>

=== XenoAmess/ArenaShooter/project/data/animations/MapXML/MapXmlPlatformMov2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE animation SYSTEM "../animationDTD.dtd" >
<animation length="16.0" loop="true">
	
	<trackVec2f name="pos" interpolation="cubic">
		<keyframeVec2f time="0.0" x="-10.0" y="-5.0" />
		<keyframeVec2f time="5.0" x="5.0" y="-5.0" />
		<keyframeVec2f time="5.5" x="30.0" y="-5.0" />
		<keyframeVec2f time="6.5" x="5.0" y="-5.0" />
		<keyframeVec2f time="8.0" x="-10.0" y="-5.0" />
		<keyframeVec2f time="8.5" x="-40.0" y="-5.0" />
		<keyframeVec2f time="16.0" x="-10.0" y="-5.0" />
	</trackVec2f>

</animation>

=== XenoAmess/ArenaShooter/project/data/animations/anim_StartCounter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE animation SYSTEM "animationDTD.dtd" >
<animation length="6.0" loop="false">

	<trackEvent>
		<keyframeEvent time ="2.0">
			<eventSound path ="data/sound/ui/count_3.ogg" channel = "UI" volume = ".5" pitch = "1" localized = "false" />
		</keyframeEvent>
		<keyframeEvent time ="3.0">
			<eventSound path ="data/sound/ui/count_2.ogg" channel = "UI" volume = ".5" pitch = "1" localized = "false" />
		</keyframeEvent>
		<keyframeEvent time ="4.0">
			<eventSound path ="data/sound/ui/count_1.ogg" channel = "UI" volume = ".5" pitch = "1" localized = "false" />
		</keyframeEvent>
		<keyframeEvent time ="5.01">
			<eventSound path ="data/sound/ui/count_fight.ogg" channel = "UI" volume = ".5" pitch = "1" localized = "false" />
		</keyframeEvent>
		<keyframeEvent time ="5.0">
			<eventCustom data="CanPlayNow" />
		</keyframeEvent>
	</trackEvent>
	
	<trackT name="CounterSprite"> 
		<keyframeT time="2.0" value = "data/sprites/interface/3_Chroma2.png" />
		<keyframeT time="3.0" value = "data/sprites/interface/2_Chroma2.png" />
		<keyframeT time="4.0" value = "data/sprites/interface/1_Chroma2.png" />
		<keyframeT time="5.00" value = "data/sprites/interface/Fight_Chroma3_01.png" />
		<keyframeT time="5.05" value = "data/sprites/interface/Fight_Chroma3_02.png" />
		<keyframeT time="5.10" value = "data/sprites/interface/Fight_Chroma3_03.png" />
		<keyframeT time="5.15" value = "data/sprites/interface/Fight_Chroma3_04.png" />
		<keyframeT time="5.20" value = "data/sprites/interface/Fight_Chroma3_05.png" />
		<keyframeT time="5.25" value = "data/sprites/interface/Fight_Chroma3_06.png" />
		<keyframeT time="5.30" value = "data/sprites/interface/Fight_Chroma3_07.png" />
		<keyframeT time="5.35" value = "data/sprites/interface/Fight_Chroma3_08.png" />
		<keyframeT time="5.40" value = "data/sprites/interface/Fight_Chroma3_09.png" />
		<keyframeT time="5.45" value = "data/sprites/interface/Fight_Chroma3_10.png" />
		<keyframeT time="5.50" value = "data/sprites/interface/Fight_Chroma3_01.png" />
		<keyframeT time="5.55" value = "data/sprites/interface/Fight_Chroma3_02.png" />
		<keyframeT time="5.60" value = "data/sprites/interface/Fight_Chroma3_03.png" />
		<keyframeT time="5.65" value = "data/sprites/interface/Fight_Chroma3_04.png" />
		<keyframeT time="5.70" value = "data/sprites/interface/Fight_Chroma3_05.png" />
		<keyframeT time="5.75" value = "data/sprites/interface/Fight_Chroma3_06.png" />
		<keyframeT time="5.80" value = "data/sprites/interface/Fight_Chroma3_07.png" />
		<keyframeT time="5.85" value = "data/sprites/interface/Fight_Chroma3_08.png" />
		<keyframeT time="5.90" value = "data/sprites/interface/Fight_Chroma3_09.png" />
		<keyframeT time="5.95" value = "data/sprites/interface/Fight_Chroma3_10.png" />
		<keyframeT time="6.00" value = "data/sprites/interface/Fight_Chroma3_01.png" />
	</trackT>
	
	<trackD name="SizeOfCounterSprite" interpolation="linear">
		<keyframeD time="2.0" value = "0.01" />
		<keyframeD time="2.2" value = "1.4" />
		<keyframeD time="2.9999" value = "1.4" />
		<keyframeD time="3.0" value = "0.01" />
		<keyframeD time="3.2" value = "1.4" />
		<keyframeD time="3.9999" value = "1.4" />	
		<keyframeD time="4.0" value = "0.01" />
		<keyframeD time="4.2" value = "1.4" />
		<keyframeD time="4.9999" value = "1.4" />
		<keyframeD time="5.0" value = "0.01" />
		<keyframeD time="5.2" value = "1.4" />
	</trackD>
	
	<trackD name="fadeToBlack" interpolation="linear">
		<keyframeD time="0.0" value = "1.0" />
		<keyframeD time="1.2" value = "0.0" />
	</trackD>


</animation>

=== XenoAmess/ArenaShooter/project/data/animations/anim_intro.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE animation SYSTEM "animationDTD.dtd" >
<animation length="15.0" loop="false">

	<trackEvent>
		<keyframeEvent time ="4.0">
			<eventSound path ="data/sound/slap.ogg" channel = "SFX" volume = ".45" pitch = "1" localized = "false" />
		</keyframeEvent>
	</trackEvent>
	
	<trackD name="fadeToBlack">
		<keyframeD time="0" value="1"/>
		<keyframeD time="1.6" value="0"/>
	</trackD>
	
	<trackVec3f name="cam_pos" interpolation="linear">
		<keyframeVec3f time="0.1" x="0" y="-4" z="50" />
		<keyframeVec3f time="4.0" x="0" y="-1.25" z="21" />
		<keyframeVec3f time="5.2" x="0" y="-1.25" z="21" />
		<keyframeVec3f time="9.0" x="0" y="-7.3" z="18" />
		<keyframeVec3f time="10.0" x="0" y="-7.3" z="18" />
		<keyframeVec3f time="11.0" x="0" y="-7.4" z="9.9" />
	</trackVec3f>
	
	<trackT name="logo_tex"> 
		<keyframeT time="0" value = "data/sprites/intro/logo_no_blood.png" />
		<keyframeT time="11" value = "data/logo.png" />
	</trackT>
	<trackD name="logo_opacity" interpolation="linear">
		<keyframeD time="9" value="0"/>
		<keyframeD time="10" value="1"/>
	</trackD>
	<trackVec3f name="logo_pos" interpolation="linear">
		<keyframeVec3f time="10.0" x="-.05" y="-7.45" z="9" />
		<keyframeVec3f time="11.0" x="-.07" y="-7.5" z="8" />
	</trackVec3f>
	<trackD name="logo_rot" interpolation="linear">
		<keyframeD time="10" value="25.13274122872"/>
		<keyframeD time="11" value="0"/>
	</trackD>
	<trackVec3f name="logo_scale" interpolation="linear">
		<keyframeVec3f time="10.0" x="2" y="2" z="1" />
		<keyframeVec3f time="11.0" x="2.3" y="2.3" z="1" />
	</trackVec3f>
	
	<trackD name="text_version_thickness" interpolation="linear">
		<keyframeD time="11" value="0.00" />
		<keyframeD time="12" value="0.25" />
	</trackD>
	
	<trackT name="cat_tex"> 
		<keyframeT time="0.0" value = "data/sprites/intro/cat_01.png" />
		<keyframeT time="0.5" value = "data/sprites/intro/cat_02.png" />
		<keyframeT time="1.0" value = "data/sprites/intro/cat_01.png" />
		<keyframeT time="1.5" value = "data/sprites/intro/cat_02.png" />
		<keyframeT time="2.0" value = "data/sprites/intro/cat_01.png" />
		<keyframeT time="2.5" value = "data/sprites/intro/cat_02.png" />
		<keyframeT time="3.0" value = "data/sprites/intro/cat_01.png" />
		<keyframeT time="3.5" value = "data/sprites/intro/cat_02.png" />
		<keyframeT time="4.0" value = "data/sprites/intro/cat_03.png" />
	</trackT>
	<trackVec3f name="cat_pos" interpolation="linear">
		<keyframeVec3f time="4.0" x="-1" y="-1" z="16.01"/>
		<keyframeVec3f time="6.0" x="-1.2" y="-.5" z="16.01"/>
	</trackVec3f>
	
	<trackT name="fox_tex"> 
		<keyframeT time="0.00" value = "data/sprites/intro/fox_01.png" />
		<keyframeT time="0.25" value = "data/sprites/intro/fox_02.png" />
		<keyframeT time="0.50" value = "data/sprites/intro/fox_01.png" />
		<keyframeT time="0.75" value = "data/sprites/intro/fox_02.png" />
		<keyframeT time="1.00" value = "data/sprites/intro/fox_01.png" />
		<keyframeT time="1.25" value = "data/sprites/intro/fox_02.png" />
		<keyframeT time="1.50" value = "data/sprites/intro/fox_01.png" />
		<keyframeT time="1.75" value = "data/sprites/intro/fox_02.png" />
		<keyframeT time="2.00" value = "data/sprites/intro/fox_01.png" />
		<keyframeT time="2.25" value = "data/sprites/intro/fox_02.png" />
		<keyframeT time="2.50" value = "data/sprites/intro/fox_01.png" />
		<keyframeT time="2.75" value = "data/sprites/intro/fox_02.png" />
		<keyframeT time="3.00" value = "data/sprites/intro/fox_01.png" />
		<keyframeT time="3.25" value = "data/sprites/intro/fox_02.png" />
		<keyframeT time="3.50" value = "data/sprites/intro/fox_01.png" />
		<keyframeT time="3.75" value = "data/sprites/intro/fox_02.png" />
		<keyframeT time="3.8" value = "data/sprites/intro/fox_03.png" />
	</trackT>
	<trackVec3f name="fox_pos" interpolation="linear">
		<keyframeVec3f time="3.8" x="1" y="-1" z="15.99"/>
		<keyframeVec3f time="4.0" x=".4" y="-1.25" z="15.99"/>
	</trackVec3f>
	<trackVec3f name="fox_scale" interpolation="linear">
		<keyframeVec3f time="3.79999" x="1.5" y="1.5" z="1"/>
		<keyframeVec3f time="3.8" x="3" y="1.5" z="1"/>
	</trackVec3f>

	<trackT name="crowd_tex"> 
		<keyframeT time="0.0" value = "data/sprites/intro/crowd_01_01.png" />
		<keyframeT time="0.5" value = "data/sprites/intro/crowd_01_02.png" />
		<keyframeT time="1.0" value = "data/sprites/intro/crowd_01_01.png" />
		<keyframeT time="1.5" value = "data/sprites/intro/crowd_01_02.png" />
		<keyframeT time="2.0" value = "data/sprites/intro/crowd_01_01.png" />
		<keyframeT time="2.5" value = "data/sprites/intro/crowd_01_02.png" />
		<keyframeT time="3.0" value = "data/sprites/intro/crowd_01_01.png" />
		<keyframeT time="3.5" value = "data/sprites/intro/crowd_01_02.png" />
		<keyframeT time="4.0" value = "data/sprites/intro/crowd_01_01.png" />
		<keyframeT time="4.5" value = "data/sprites/intro/crowd_01_02.png" />
		<keyframeT time="5.0" value = "data/sprites/intro/crowd_01_01.png" />
		<keyframeT time="5.5" value = "data/sprites/intro/crowd_01_02.png" />
		<keyframeT time="6.0" value = "data/sprites/intro/crowd_01_01.png" />
		<keyframeT time="6.5" value = "data/sprites/intro/crowd_01_02.png" />
		<keyframeT time="7.0" value = "data/sprites/intro/crowd_01_01.png" />
		<keyframeT time="7.5" value = "data/sprites/intro/crowd_01_02.png" />
		<keyframeT time="8.0" value = "data/sprites/intro/crowd_01_01.png" />
		<keyframeT time="8.5" value = "data/sprites/intro/crowd_01_02.png" />
	</trackT>

</animation>

=== XenoAmess/ArenaShooter/project/data/animations/animTest2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE animation SYSTEM "animationDTD.dtd" >
<animation length="5.0" loop="true">
	
	<trackVec2f name="rightPos" interpolation="cubic">
		<keyframeVec2f time="0.0" x="0.0" y="0.0" />
		<keyframeVec2f time="2.0" x="0.0" y="0.0" />
		<keyframeVec2f time="3.0" x="0.0" y="0.0" />
		<keyframeVec2f time="4.0" x="0.0" y="0.0" />
		<keyframeVec2f time="5.0" x="0.0" y="0.0" />
	</trackVec2f>

	<trackD name="rightRot" interpolation="cubic">
		<keyframeD time="0.0" value="0.75" />
		<keyframeD time="2.0" value="1.57" />
		<keyframeD time="3.0" value="-0.5" />
		<keyframeD time="4.0" value="-1.0" />
		<keyframeD time="5.0" value="-1.57" />
	</trackD>
	
	<trackVec2f name="leftPos" interpolation="cubic">
		<keyframeVec2f time="0.0" x="0.0" y="0.0" />
		<keyframeVec2f time="2.0" x="0.0" y="0.0" />
		<keyframeVec2f time="3.0" x="0.0" y="0.0" />
		<keyframeVec2f time="4.0" x="0.0" y="0.0" />
		<keyframeVec2f time="5.0" x="0.0" y="0.0" />
	</trackVec2f>
	
	<trackD name="leftRot" interpolation="cubic">
		<keyframeD time="0.0" value="-0.75" />
		<keyframeD time="2.0" value="-1.57" />
		<keyframeD time="3.0" value="0.5" />
		<keyframeD time="4.0" value="1.0" />
		<keyframeD time="5.0" value="1.57" />
	</trackD>

</animation>
