=== XenoAmess/ArenaShooter/res/data/mapXML/mapDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT map (information , entity*)>
<!ELEMENT information (spawn+ , gravity , cameraBound)>
<!ELEMENT entity (plateform)*>
<!ELEMENT spawn (position)>
<!ELEMENT gravity (#PCDATA)>
<!ELEMENT cameraBound EMPTY>
<!ATTLIST cameraBound x CDATA #REQUIRED y CDATA #REQUIRED z CDATA #REQUIRED w CDATA #REQUIRED>
<!ELEMENT plateform (position , position)>
<!ELEMENT position EMPTY>
<!ATTLIST position x CDATA #REQUIRED y CDATA #REQUIRED z CDATA #IMPLIED>
<!ELEMENT fichier (#PCDATA)>

=== XenoAmess/ArenaShooter/res/data/mapXML/mapXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map SYSTEM "mapDTD.dtd" >
<map>
  <information>
    <spawn>
      <position x="-300" y="0"/>
    </spawn>
    <spawn>
      <position x="300" y="0"/>
    </spawn>
    <gravity>9.807</gravity>
    <cameraBound w="1000" x="-5000" y="-1000" z="5000"/>
  </information>
  <entity>
  	<plateform>
  		<position x="0" y="510"/>
  		<position x="1500" y="100"/>
  	</plateform>
  	<plateform>
  		<position x="-800" y="210"/>
  		<position x="300" y="300"/>
  	</plateform>
  </entity>
</map>
