=== XenoAmess/ArenaShooter/editor/export/mapDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT map (information , entities , items?)>
<!ATTLIST map name CDATA #IMPLIED>

<!-- Map info -->
<!ELEMENT information (spawn+ , gravity , cameraBound , sky)>
<!ELEMENT spawn (vecteur)>
<!ELEMENT gravity (vecteur)>
<!ELEMENT cameraBound EMPTY>
<!ATTLIST cameraBound x CDATA #REQUIRED y CDATA #REQUIRED z CDATA #REQUIRED w CDATA #REQUIRED>
<!ELEMENT sky (vecteur, vecteur)>

<!-- Entities-->
<!ELEMENT entities (entity|plateform|mesh|text)*>
<!ELEMENT entity (entities?)>
<!ATTLIST entity name CDATA #IMPLIED>
<!ELEMENT plateform (vecteur , vecteur, entities?)>
<!ATTLIST plateform name CDATA #IMPLIED>
<!ELEMENT mesh (vecteur, vecteur, vecteur, entities?)>
<!ATTLIST mesh name CDATA #IMPLIED>
<!ATTLIST mesh src CDATA #REQUIRED>
<!ELEMENT text (vecteur, vecteur, entities?)>
<!ATTLIST text name CDATA #IMPLIED>
<!ATTLIST text content CDATA #REQUIRED>
<!ATTLIST text font CDATA #REQUIRED>

<!-- Misc -->
<!ELEMENT vecteur EMPTY>
<!ATTLIST vecteur w CDATA #IMPLIED x CDATA #REQUIRED y CDATA #REQUIRED z CDATA #IMPLIED use CDATA #IMPLIED >
<!ELEMENT fichier (#PCDATA)>

<!-- Items allowed -->
<!ELEMENT items (equipement | weapon | melee)*>
<!ELEMENT equipement EMPTY>
<!ELEMENT weapon (vecteur , entities?)>
<!ATTLIST weapon name CDATA #IMPLIED
				 damage CDATA #IMPLIED
				 fireRate CDATA #IMPLIED
				 thrust CDATA #IMPLIED
				 recoil CDATA #IMPLIED
				 tpsCharge CDATA #IMPLIED
				 chargeInertia CDATA #IMPLIED
				 spritePath CDATA #IMPLIED
				 clickSoundPath CDATA #IMPLIED
				 bangSoundPath CDATA #IMPLIED
				 pickupSound CDATA #IMPLIED
				 chargeSoundPath CDATA #IMPLIED
				 noAmmoSound CDATA #IMPLIED
				 bulletType CDATA #IMPLIED
				 bulletSpeed CDATA #IMPLIED
				 cannonLength CDATA #IMPLIED
				 
				 type CDATA #REQUIRED
				 proba CDATA #REQUIRED
				 size CDATA #REQUIRED>
<!ELEMENT melee (vecteur, entities?)>
<!ATTLIST melee name CDATA #IMPLIED
				damage CDATA #IMPLIED
				bangSound CDATA #IMPLIED
				spritePath CDATA #IMPLIED
				fireRate CDATA #IMPLIED
				type CDATA #REQUIRED
				 proba CDATA #REQUIRED
				 size CDATA #REQUIRED
				>

=== XenoAmess/ArenaShooter/project/data/mapXML/Slaughterhouse.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map SYSTEM "mapDTD.dtd" >
<map>
	<information>
		<spawn spawnperso="true" cooldown="2">
			<vecteur x="-15" y="-1.2" />
		</spawn>
		<spawn spawnperso="true" cooldown="2">
			<vecteur x="-5" y="-1.2" />
		</spawn>
		<spawn spawnperso="true" cooldown="2">
			<vecteur x="5" y="-1.2" />
		</spawn>
		<spawn spawnperso="true" cooldown="2">
			<vecteur x="15" y="-1.2" />
		</spawn>
		
		<spawn spawnperso="false" cooldown="5">
			<vecteur x="-5" y="-16.5" />
			<gun name="Minigun" weight="43"
				pathSprite="data/weapons/Minigun_1.png" soundPickup="GunCock_02"
				cooldown="0.03" uses="350" animPath="" warmupDuration="0.25"
				soundWarmup="warmup_minigun_01" bangSound="Bang1"
				noAmmoSound="no_ammo_01" bulletType="0" bulletSpeed="35" damage="1"
				cannonLength="1.9" recoil="0.2" thrust="2.6" size="64" proba="1">

				<vecteur use="handPosL" x="-.8" y="-.1" />
				<vecteur use="handPosR" x="0" y="-.28" />
			</gun>
			<gun name="assault" weight="43"
				pathSprite="data/weapons/Assaut_1.png" soundPickup="GunCock_01"
				cooldown="0.09" uses="50" animPath="" warmupDuration="0"
				soundWarmup="" bangSound="bang_tommy_gun_01"
				noAmmoSound="no_ammo_01" bulletType="0" bulletSpeed="35" damage="1"
				cannonLength="1.38" recoil="0.4" thrust="2.00" size="64" proba="1">

				<vecteur use="handPosL" x="-.32" y=".15" />
				<vecteur use="handPosR" x=".25" y=".05" />
			</gun>
			<gun name="ion" weight="50"
				pathSprite="data/weapons/RayGun1_tr.png" soundPickup="GunCock_03"
				cooldown="0.12" uses="100" animPath="" warmupDuration="0.8"
				soundWarmup="IonCharge3" bangSound="BangIonGun"
				noAmmoSound="no_ammo_01" bulletType="1" bulletSpeed="30" damage="1"
				cannonLength="1.38" recoil="1" thrust="2.00" size="64" proba="1">

				<vecteur use="handPosL" x="-.32" y=".2" />
				<vecteur use="handPosR" x=".3" y=".1" />
			</gun>
			<shotgun name="shotgun" weight="100"
				pathSprite="data/weapons/shotgun1.png" soundPickup="GunCock_02"
				cooldown="1.2" uses="8" animPath="" warmupDuration="0"
				soundWarmup="" bangSound="bang_shotgun_01" noAmmoSound="no_ammo_01"
				multiShot="25" dispersion="0.18" bulletType="0" bulletSpeed="45"
				damage="2" cannonLength=".6" recoil="2" thrust="25.00" size="2"
				proba="1">

				<vecteur use="handPosL" x="-.65" y=".15" />
				<vecteur use="handPosR" x=".067" y=".125" />
			</shotgun>
			<gun name="grenade_launcher" weight="50"
				pathSprite="data/weapons/GLauncher1.png" soundPickup="GunCock_01"
				cooldown="0.9" uses="10" animPath="" warmupDuration="0"
				soundWarmup=""
				bangSound="grenade_launcher_01"
				noAmmoSound="no_ammo_01" bulletType="2"
				bulletSpeed="30" damage="95" cannonLength="1.38" recoil="1"
				thrust="2.00" size="64" proba="1">

				<vecteur use="handPosL" x="-.32" y=".2" />
				<vecteur use="handPosR" x=".3" y=".1" />
			</gun>
			<entities>
				<mesh src="data/meshes/item_pickup/weapon_pickup_ceiling.obj">
					<vecteur use="position" x="0" y="-1" z="0" />
					<vecteur use="rotation" x="0" y="0" z="0" w="1" />
					<vecteur use="scale" x=".75" y=".75" z=".75" />
				</mesh>
			</entities>
		</spawn>

		<spawn spawnperso="false" cooldown="5">
			<vecteur x="15" y="-16.5" />
			<gun name="Minigun" weight="43"
				pathSprite="data/weapons/Minigun_1.png" soundPickup="GunCock_02"
				cooldown="0.03" uses="350" animPath="" warmupDuration="0.25"
				soundWarmup="warmup_minigun_01" bangSound="Bang1"
				noAmmoSound="no_ammo_01" bulletType="0" bulletSpeed="35" damage="1"
				cannonLength="1.9" recoil="0.2" thrust="2.6" size="64" proba="1">

				<vecteur use="handPosL" x="-.8" y="-.1" />
				<vecteur use="handPosR" x="0" y="-.28" />
			</gun>
			<gun name="assault" weight="43"
				pathSprite="data/weapons/Assaut_1.png" soundPickup="GunCock_01"
				cooldown="0.09" uses="100" animPath="" warmupDuration="0"
				soundWarmup="" bangSound="bang_tommy_gun_01"
				noAmmoSound="no_ammo_01" bulletType="0" bulletSpeed="35" damage="1"
				cannonLength="1.38" recoil="0.4" thrust="2.00" size="64" proba="1">

				<vecteur use="handPosL" x="-.32" y=".15" />
				<vecteur use="handPosR" x=".25" y=".05" />
			</gun>
			<gun name="ion" weight="50"
				pathSprite="data/weapons/RayGun1_tr.png" soundPickup="GunCock_03"
				cooldown="0.12" uses="100" animPath="" warmupDuration="0.8"
				soundWarmup="IonCharge3" bangSound="BangIonGun"
				noAmmoSound="no_ammo_01" bulletType="1" bulletSpeed="30" damage="1"
				cannonLength="1.38" recoil="1" thrust="2.00" size="64" proba="1">

				<vecteur use="handPosL" x="-.32" y=".3" />
				<vecteur use="handPosR" x=".3" y=".1" />
			</gun>
			<shotgun name="shotgun" weight="100"
				pathSprite="data/weapons/shotgun1.png" soundPickup="GunCock_02"
				cooldown="1.2" uses="8" animPath="" warmupDuration="0"
				soundWarmup="" bangSound="bang_shotgun_01" noAmmoSound="no_ammo_01"
				multiShot="25" dispersion="0.18" bulletType="0" bulletSpeed="45"
				damage="2" cannonLength=".6" recoil="2" thrust="25.00" size="2"
				proba="1">

				<vecteur use="handPosL" x="-.65" y=".15" />
				<vecteur use="handPosR" x=".067" y=".125" />
			</shotgun>
			<gun name="grenade_launcher" weight="50"
				pathSprite="data/weapons/GLauncher1.png" soundPickup="GunCock_01"
				cooldown="0.9" uses="10" animPath="" warmupDuration="0"
				soundWarmup=""
				bangSound="grenade_launcher_01"
				noAmmoSound="no_ammo_01" bulletType="2"
				bulletSpeed="30" damage="95" cannonLength="1.38" recoil="1"
				thrust="2.00" size="64" proba="1">

				<vecteur use="handPosL" x="-.32" y=".2" />
				<vecteur use="handPosR" x=".3" y=".1" />
			</gun>
			<melee name="kata" weight="5"
				pathSprite="data/weapons/sword_01.png" soundPickup="sword_draw_01"
				cooldown="1.0" uses="350" animPath="" warmupDuration="0.1"
				soundWarmup="" damage="3" bangSound="woosh_01" size="2" proba="1">

				<vecteur use="handPosL" x="-50" y="0" />
				<vecteur use="handPosR" x="0" y="0" />
			</melee>
			<entities>
				<mesh src="data/meshes/item_pickup/weapon_pickup_ceiling.obj">
					<vecteur use="position" x="0" y="-1" z="0" />
					<vecteur use="rotation" x="0" y="0" z="0" w="1" />
					<vecteur use="scale" x=".75" y=".75" z=".75" />
				</mesh>
			</entities>
		</spawn>
		
		<spawn spawnperso="false" cooldown="5">
			<vecteur x="-15" y="-16.5" />
			<gun name="Minigun" weight="43"
				pathSprite="data/weapons/Minigun_1.png" soundPickup="GunCock_02"
				cooldown="0.03" uses="350" animPath="" warmupDuration="0.25"
				soundWarmup="warmup_minigun_01" bangSound="Bang1"
				noAmmoSound="no_ammo_01" bulletType="0" bulletSpeed="35" damage="1"
				cannonLength="1.9" recoil="0.2" thrust="2.6" size="64" proba="1">

				<vecteur use="handPosL" x="-.8" y="-.1" />
				<vecteur use="handPosR" x="0" y="-.28" />
			</gun>
			<gun name="assault" weight="43"
				pathSprite="data/weapons/Assaut_1.png" soundPickup="GunCock_01"
				cooldown="0.09" uses="100" animPath="" warmupDuration="0"
				soundWarmup="" bangSound="bang_tommy_gun_01"
				noAmmoSound="no_ammo_01" bulletType="0" bulletSpeed="35" damage="1"
				cannonLength="1.38" recoil="0.4" thrust="2.00" size="64" proba="1">

				<vecteur use="handPosL" x="-.32" y=".15" />
				<vecteur use="handPosR" x=".25" y=".05" />
			</gun>
			<gun name="ion" weight="50"
				pathSprite="data/weapons/RayGun1_tr.png" soundPickup="GunCock_03"
				cooldown="0.12" uses="100" animPath="" warmupDuration="0.8"
				soundWarmup="IonCharge3" bangSound="BangIonGun"
				noAmmoSound="no_ammo_01" bulletType="1" bulletSpeed="30" damage="1"
				cannonLength="1.38" recoil="1" thrust="2.00" size="64" proba="1">

				<vecteur use="handPosL" x="-.32" y=".3" />
				<vecteur use="handPosR" x=".3" y=".1" />
			</gun>
			<shotgun name="shotgun" weight="100"
				pathSprite="data/weapons/shotgun1.png" soundPickup="GunCock_02"
				cooldown="1.2" uses="8" animPath="" warmupDuration="0"
				soundWarmup="" bangSound="bang_shotgun_01" noAmmoSound="no_ammo_01"
				multiShot="25" dispersion="0.18" bulletType="0" bulletSpeed="45"
				damage="2" cannonLength=".6" recoil="2" thrust="25.00" size="2"
				proba="1">

				<vecteur use="handPosL" x="-.65" y=".15" />
				<vecteur use="handPosR" x=".067" y=".125" />
			</shotgun>
			<gun name="grenade_launcher" weight="50"
				pathSprite="data/weapons/GLauncher1.png" soundPickup="GunCock_01"
				cooldown="0.9" uses="10" animPath="" warmupDuration="0"
				soundWarmup=""
				bangSound="grenade_launcher_01"
				noAmmoSound="no_ammo_01" bulletType="2"
				bulletSpeed="30" damage="95" cannonLength="1.38" recoil="1"
				thrust="2.00" size="64" proba="1">

				<vecteur use="handPosL" x="-.32" y=".2" />
				<vecteur use="handPosR" x=".3" y=".1" />
			</gun>
			<melee name="kata" weight="5"
				pathSprite="data/weapons/sword_01.png" soundPickup="sword_draw_01"
				cooldown="1.0" uses="350" animPath="" warmupDuration="0.1"
				soundWarmup="" damage="3" bangSound="woosh_01" size="2" proba="1">

				<vecteur use="handPosL" x="-50" y="0" />
				<vecteur use="handPosR" x="0" y="0" />
			</melee>
			<entities>
				<mesh src="data/meshes/item_pickup/weapon_pickup_ceiling.obj">
					<vecteur use="position" x="0" y="-1" z="0" />
					<vecteur use="rotation" x="0" y="0" z="0" w="1" />
					<vecteur use="scale" x=".75" y=".75" z=".75" />
				</mesh>
			</entities>
		</spawn>
		<spawn spawnperso="false" cooldown="5">
			<vecteur x="5" y="-16.5" />
			<gun name="Minigun" weight="43"
				pathSprite="data/weapons/Minigun_1.png" soundPickup="GunCock_02"
				cooldown="0.03" uses="350" animPath="" warmupDuration="0.25"
				soundWarmup="warmup_minigun_01" bangSound="Bang1"
				noAmmoSound="no_ammo_01" bulletType="0" bulletSpeed="35" damage="1"
				cannonLength="1.9" recoil="0.2" thrust="2.6" size="64" proba="1">
