=== XenoAmess/ArenaShooter/project/data/particles/particlesDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT particleSystem (emitter+)>

<!ELEMENT emitter (texture, modules)>
<!ATTLIST emitter duration CDATA #REQUIRED>
<!ATTLIST emitter delay CDATA #REQUIRED>
<!ATTLIST emitter rate CDATA #REQUIRED>
<!ATTLIST emitter lifetimeMin CDATA #REQUIRED>
<!ATTLIST emitter lifetimeMax CDATA #REQUIRED>
<!ATTLIST emitter initialRotMin CDATA #REQUIRED>
<!ATTLIST emitter initialRotMax CDATA #REQUIRED>

<!ELEMENT modules (accelConstant|colorOverLife|gravity|initialPosCircle|initialVelCone|sizeOverLife)*>

<!-- Modules -->

<!ELEMENT accelConstant (vec2)>

<!-- colorStart, colorEnd -->
<!ELEMENT colorOverLife (vec4, vec4)>

<!ELEMENT drag EMPTY>
<!ATTLIST drag strength CDATA #REQUIRED>

<!ELEMENT gravity EMPTY>
<!ATTLIST gravity gravityScale CDATA #REQUIRED>

<!ELEMENT initialPosCircle EMPTY>
<!ATTLIST initialPosCircle radiusMin CDATA #REQUIRED>
<!ATTLIST initialPosCircle radiusMax CDATA #REQUIRED>

<!ELEMENT initialVelCone EMPTY>
<!ATTLIST initialVelCone angleMin CDATA #REQUIRED>
<!ATTLIST initialVelCone angleMax CDATA #REQUIRED>
<!ATTLIST initialVelCone velMin CDATA #REQUIRED>
<!ATTLIST initialVelCone velMax CDATA #REQUIRED>

<!-- sizeStart, sizeEnd -->
<!ELEMENT sizeOverLife (vec2, vec2)>


<!-- Misc -->

<!ELEMENT vec2 EMPTY>
<!ATTLIST vec2 use CDATA #IMPLIED x CDATA #REQUIRED y CDATA #REQUIRED>

<!ELEMENT vec4 EMPTY>
<!ATTLIST vec4 use CDATA #IMPLIED x CDATA #REQUIRED y CDATA #REQUIRED z CDATA #REQUIRED w CDATA #REQUIRED>

<!ELEMENT texture EMPTY>
<!ATTLIST texture src CDATA #REQUIRED filtered CDATA #REQUIRED>

=== XenoAmess/ArenaShooter/project/data/particles/blood.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE particleSystem SYSTEM "particlesDTD.dtd" >
<particleSystem>
	<emitter delay="0" duration="0" lifetimeMin="1" lifetimeMax="1.5" rate="1" initialRotMin="-3.14159" initialRotMax="3.14159">
		<texture filtered="false" src="data/particle_glow.png"/>
		<modules>
			<colorOverLife>
				<vec4 x="1" y="0" z="0" w="1" use="colorStart"/>
				<vec4 x="1" y="0.1" z="0" w="0.3" use="colorEnd"/>
			</colorOverLife>
			<sizeOverLife>
				<vec2 x=".2" y=".2" use="sizeStart"/>
				<vec2 x="0" y="0" use="sizeEnd"/>
			</sizeOverLife>
			<initialVelCone angleMin="-.2" angleMax=".2" velMin="50" velMax="75"/>
		</modules>
	</emitter>

	<!-- 
	<emitter angleMin="-.2" angleMax=".2" delay="0" duration="0" lifetimeMin="0.10" lifetimeMax=".3" rate="5" velocityMin="50" velocityMax="75" gravityScale="0">
	<basic sizeInitial=".2" sizeEnd="0"></basic>
	<texture filtered="false" src="data/particle_glow.png"/>
	<vec4 x="1" y="0" z="0" w="1" use="colorStart"/>
	<vec4 x="1" y=".1" z="0" w=".3" use="colorEnd"/>
	</emitter>
	 -->
</particleSystem>

=== XenoAmess/ArenaShooter/project/data/particles/explosion.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE particleSystem SYSTEM "particlesDTD.dtd" >
<particleSystem>
	<emitter angleMin="-3.14159" angleMax="3.14159" delay="0" duration="0" lifetimeMin="1" lifetimeMax="1.2" rate="1" velocityMin="0" velocityMax="0" gravityScale="0">
	<basic sizeInitial="3" sizeEnd="21"></basic>
	<texture filtered="true" src="data/particles/flash_01.png"/>
	<vec4 x="2" y="2" z="2" w="1" use="colorStart"/>
	<vec4 x=".3" y=".05" z=".05" w="0" use="colorEnd"/>
	</emitter>

	<emitter angleMin="-3.14159" angleMax="3.14159" delay="0" duration="0" lifetimeMin="4" lifetimeMax="6" rate="35" velocityMin="15" velocityMax="40" gravityScale="3">
	<basic sizeInitial=".2" sizeEnd="0"></basic>
<!-- 	<oriented><vec2 x="10.5" y="10.15"/></oriented> -->
	<texture filtered="false" src="data/particle_glow.png"/>
	<vec4 x="2" y="1.714" z="0.290" w="1" use="colorStart"/>
	<vec4 x=".4" y=".1" z="0" w="0" use="colorEnd"/>
	</emitter>
</particleSystem>

=== XenoAmess/ArenaShooter/project/data/particles/shell_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE particleSystem SYSTEM "particlesDTD.dtd" >
<particleSystem>
	<emitter delay="0" duration="0" lifetimeMin="1" lifetimeMax="1.5" rate="1" initialRotMin="-1.57" initialRotMax="0">
		<texture filtered="false" src="data/particles/shell_01.png"/>
		<modules>
			<colorOverLife>
				<vec4 x="1" y="1" z="1" w="1" use="colorStart"/>
				<vec4 x="1" y="1" z="1" w="0" use="colorEnd"/>
			</colorOverLife>
			<sizeOverLife>
				<vec2 x=".4" y=".4" use="sizeStart"/>
				<vec2 x=".4" y=".4" use="sizeEnd"/>
			</sizeOverLife>
			<gravity gravityScale="5"/>
			<initialVelCone angleMin="-1.57" angleMax="0" velMin="8" velMax="15"/>
		</modules>
	</emitter>
	
	<!--
	<emitter angleMin="-1.57" angleMax="0" delay="0" duration="0" lifetimeMin="1" lifetimeMax="1.5" rate="1" velocityMin="8" velocityMax="15" gravityScale="5">
	<basic sizeInitial=".4" sizeEnd=".4"></basic>
	<texture filtered="false" src="data/particles/shell_01.png"/>
	<vec4 x="1" w="1" z="1" y="1" use="colorStart"/>
	<vec4 x="1" w="0" z="1" y="1" use="colorEnd"/>
	</emitter>
	-->
</particleSystem>

=== XenoAmess/ArenaShooter/project/data/particles/Fuse.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE particleSystem SYSTEM "particlesDTD.dtd" >
<particleSystem>
	<emitter delay="0" duration="3" lifetimeMin=".05" lifetimeMax=".1" rate="80" initialRotMin="0" initialRotMax="0">
		<texture filtered="false" src="data/particles/spark.png"/>
		<modules>
			<colorOverLife>
				<vec4 x="4" y="2" z="1" w="1" use="colorStart"/>
				<vec4 x=".9" y=".4" z=".1" w=".5" use="colorEnd"/>
			</colorOverLife>
			<sizeOverLife>
				<vec2 x=".08" y=".08" use="sizeStart"/>
				<vec2 x=".08" y=".08" use="sizeEnd"/>
			</sizeOverLife>
			<initialVelCone angleMin=".03" angleMax=".03" velMin="75" velMax="110"/>
		</modules>
	</emitter>


<!--	<emitter angleMin="1.407" angleMax="1.607" delay="0" duration="3" lifetimeMin="0.05" lifetimeMax="0.1" rate="80" velocityMin="30" velocityMax="50" gravityScale=".3">
	<basic sizeInitial=".04" sizeEnd=".04"></basic>
<!--	<oriented><vec2 x="10.5" y="10.15"/></oriented>
	<texture filtered="false" src="data/white_pixel.png"/>
	<vec4 x="1" y="0.9" z="0.7" w="1" use="colorStart"/>
	<vec4 x=".2" y="0" z="0" w="1" use="colorEnd"/>
	</emitter>-->
</particleSystem>
