=== XenoAmess/ArenaShooter/project/data/mapXML/mapDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT map (information , entities*)>

<!-- Map info -->
<!ELEMENT information (spawn+ , gravity , cameraBound , sky)>
<!ELEMENT spawn (vecteur)>
<!ELEMENT gravity (vecteur)>
<!ELEMENT cameraBound EMPTY>
<!ATTLIST cameraBound x CDATA #REQUIRED y CDATA #REQUIRED z CDATA #REQUIRED w CDATA #REQUIRED>
<!ELEMENT sky (vecteur, vecteur)>

<!-- Entities-->
<!ELEMENT entities (entity*, plateform*, weapon*, mesh*)>
<!ELEMENT entity (entities?)>
<!ELEMENT plateform (vecteur , vecteur, entities?)>
<!ELEMENT weapon (vecteur, vecteur, entities?)>
<!ELEMENT mesh (vecteur, vecteur, entities?)>
<!ATTLIST mesh src CDATA #REQUIRED>

<!-- Misc -->
<!ELEMENT vecteur EMPTY>
<!ATTLIST vecteur x CDATA #REQUIRED y CDATA #REQUIRED z CDATA #IMPLIED use CDATA #IMPLIED >
<!ELEMENT fichier (#PCDATA)>

=== XenoAmess/ArenaShooter/project/data/Obsolete_Maps/TENDEM.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE map SYSTEM "mapDTD.dtd">
<map>
  <information>
    <spawn cooldown="4" spawnperso="true">
      <vecteur x="555.0" y="990.0"/>
      			<gun name="Minigun" weight="43"
				pathSprite="data/weapons/Minigun_1.png" soundPickup="GunCock_02"
				cooldown="0.03" uses="350" animPath="" warmupDuration="0.25"
				soundWarmup="warmup_minigun_01" bangSound="Bang1"
				noAmmoSound="no_ammo_01" bulletType="0" bulletSpeed="3500"
				damage="1" cannonLength="100" recoil="0.2" thrust="275" size="64"
				proba="1">

				<vecteur use="handPosL" x="-25" y="6" />
				<vecteur use="handPosR" x="3" y="3" />
			</gun>
			<gun name="assault" weight="43"
				pathSprite="data/weapons/Assaut_1.png" soundPickup="GunCock_01"
				cooldown="0.09" uses="100" animPath="" warmupDuration="0"
				soundWarmup="" bangSound="bang_tommy_gun_01"
				noAmmoSound="no_ammo_01" bulletType="0" bulletSpeed="3500"
				damage="1" cannonLength="58" recoil="1.6" thrust="200" size="64"
				proba="1">

				<vecteur use="handPosL" x="-25" y="8" />
				<vecteur use="handPosR" x="3" y="4" />
			</gun>
			<gun name="ion" weight="50"
				pathSprite="data/weapons/RayGun1_tr.png" soundPickup="GunCock_03"
				cooldown="0.12" uses="100" animPath="" warmupDuration="0.8"
				soundWarmup="IonCharge3" bangSound="BangIonGun"
				noAmmoSound="no_ammo_01" bulletType="1" bulletSpeed="3000"
				damage="1" cannonLength="50" recoil="1" thrust="200" size="64"
				proba="1">

				<vecteur use="handPosL" x="-25" y="6" />
				<vecteur use="handPosR" x="3" y="3" />
			</gun>
			<shotgun name="shotgun" weight="100"
				pathSprite="data/weapons/shotgun1.png" soundPickup="GunCock_02"
				cooldown="1.2" uses="6" animPath="" warmupDuration="0"
				soundWarmup="" bangSound="bang_shotgun_01" noAmmoSound="no_ammo_01"
				multiShot="25" dispersion="0.3" bulletType="0" bulletSpeed="3200"
				damage="2" cannonLength="60" recoil="2" thrust="2500" size="2"
				proba="1">

				<vecteur use="handPosL" x="15" y="0" />
				<vecteur use="handPosR" x="5" y="0" />
			</shotgun>
			<entities>
				<mesh src="data/meshes/item_pickup/weapon_pickup.obj">
					<vecteur use="position" x="0" y="40" z="0" />
					<vecteur use="rotation" x="0" y="0" z="0" w="1" />
					<vecteur use="scale" x="35" y="35" z="35" />
				</mesh>
			</entities>
      
    </spawn>
    <spawn cooldown="4" spawnperso="true">
      <vecteur x="1665.0" y="1270.0"/>
    				<gun name="Minigun" weight="43"
				pathSprite="data/weapons/Minigun_1.png" soundPickup="GunCock_02"
				cooldown="0.03" uses="350" animPath="" warmupDuration="0.25"
				soundWarmup="warmup_minigun_01" bangSound="Bang1"
				noAmmoSound="no_ammo_01" bulletType="0" bulletSpeed="3500"
				damage="1" cannonLength="100" recoil="0.2" thrust="275" size="64"
				proba="1">

				<vecteur use="handPosL" x="-25" y="6" />
				<vecteur use="handPosR" x="3" y="3" />
			</gun>
			<gun name="assault" weight="43"
				pathSprite="data/weapons/Assaut_1.png" soundPickup="GunCock_01"
				cooldown="0.09" uses="100" animPath="" warmupDuration="0"
				soundWarmup="" bangSound="bang_tommy_gun_01"
				noAmmoSound="no_ammo_01" bulletType="0" bulletSpeed="3500"
				damage="1" cannonLength="58" recoil="1.6" thrust="200" size="64"
				proba="1">

				<vecteur use="handPosL" x="-25" y="8" />
				<vecteur use="handPosR" x="3" y="4" />
			</gun>
			<gun name="ion" weight="50"
				pathSprite="data/weapons/RayGun1_tr.png" soundPickup="GunCock_03"
				cooldown="0.12" uses="100" animPath="" warmupDuration="0.8"
				soundWarmup="IonCharge3" bangSound="BangIonGun"
				noAmmoSound="no_ammo_01" bulletType="1" bulletSpeed="3000"
				damage="1" cannonLength="50" recoil="1" thrust="200" size="64"
				proba="1">

				<vecteur use="handPosL" x="-25" y="6" />
				<vecteur use="handPosR" x="3" y="3" />
			</gun>
			<shotgun name="shotgun" weight="100"
				pathSprite="data/weapons/shotgun1.png" soundPickup="GunCock_02"
				cooldown="1.2" uses="6" animPath="" warmupDuration="0"
				soundWarmup="" bangSound="bang_shotgun_01" noAmmoSound="no_ammo_01"
				multiShot="25" dispersion="0.3" bulletType="0" bulletSpeed="3200"
				damage="2" cannonLength="60" recoil="2" thrust="2500" size="2"
				proba="1">

				<vecteur use="handPosL" x="15" y="0" />
				<vecteur use="handPosR" x="5" y="0" />
			</shotgun>
			<entities>
				<mesh src="data/meshes/item_pickup/weapon_pickup.obj">
					<vecteur use="position" x="0" y="40" z="0" />
					<vecteur use="rotation" x="0" y="0" z="0" w="1" />
					<vecteur use="scale" x="35" y="35" z="35" />
				</mesh>
			</entities>
    	
    </spawn>
    <spawn cooldown="4" spawnperso="true">
      <vecteur x="1515.0" y="1581.0"/>
    </spawn>
    <spawn cooldown="4" spawnperso="true">
      <vecteur x="1181.0" y="1621.0"/>
    </spawn>
    <spawn cooldown="4" spawnperso="true">
      <vecteur x="940.0" y="1509.0"/>
    </spawn>
    <spawn cooldown="4" spawnperso="true">
      <vecteur x="884.0" y="981.0"/>
    </spawn>
    <spawn cooldown="4" spawnperso="true">
      <vecteur x="1321.0" y="1221.0"/>
    </spawn>
    <spawn cooldown="4" spawnperso="true">
      <vecteur x="2040.0" y="1021.0"/>
    </spawn>
    <spawn cooldown="4" spawnperso="true">
      <vecteur x="1881.0" y="765.0"/>
    </spawn>
    <spawn cooldown="4" spawnperso="true">
      <vecteur x="537.0" y="518.0"/>
    </spawn>
    <spawn cooldown="4" spawnperso="true">
      <vecteur x="2206.0" y="656.0"/>
    </spawn>
    <gravity>
      <vecteur x="0.0" y="9.807"/>
    </gravity>
    <cameraBound w="1000" x="-5000" y="-1000" z="5000"/>
    <sky>
      <vecteur use="top" x="1.0" y="1.0" z="1.0"/>
      <vecteur use="bottom" x="1.0" y="1.0" z="1.0"/>
    </sky>
  </information>
  <entities>
    <plateform name="Platform_112914452335756">
      <vecteur use="position" x="1950.0" y="920.0"/>
      <vecteur use="extent" x="150.0" y="10.0"/>
    </plateform>
    <plateform name="Platform_112942391715285">
      <vecteur use="position" x="1970.0" y="1500.0"/>
      <vecteur use="extent" x="150.0" y="260.0"/>
    </plateform>
    <plateform name="Platform_112916870225275">
      <vecteur use="position" x="860.0" y="1150.0"/>
      <vecteur use="extent" x="150.0" y="10.0"/>
    </plateform>
    <plateform name="Platform_112951185004082">
      <vecteur use="position" x="1630.0" y="1400.0"/>
      <vecteur use="extent" x="150.0" y="10.0"/>
    </plateform>
    <plateform name="Platform_112962950967978">
      <vecteur use="position" x="1930.0" y="1400.0"/>
      <vecteur use="extent" x="150.0" y="10.0"/>
    </plateform>
    <plateform name="Platform_113117648977621">
      <vecteur use="position" x="280.0" y="890.0"/>
      <vecteur use="extent" x="150.0" y="260.0"/>
    </plateform>
    <plateform name="Platform_113132263142783">
      <vecteur use="position" x="570.0" y="640.0"/>
      <vecteur use="extent" x="150.0" y="10.0"/>
    </plateform>
    <plateform name="Platform_113093640526062">
      <vecteur use="position" x="2260.0" y="990.0"/>
      <vecteur use="extent" x="150.0" y="260.0"/>
    </plateform>
    <plateform name="Platform_112938386266838">
      <vecteur use="position" x="1470.0" y="1770.0"/>
      <vecteur use="extent" x="650.0" y="10.0"/>
    </plateform>
    <plateform name="Platform_112924758937226">
      <vecteur use="position" x="860.0" y="1900.0"/>
      <vecteur use="extent" x="150.0" y="260.0"/>
    </plateform>
    <plateform name="Platform_112939914629739">
      <vecteur use="position" x="1340.0" y="1400.0"/>
      <vecteur use="extent" x="150.0" y="10.0"/>
    </plateform>
    <plateform name="Platform_112918657612292">
      <vecteur use="position" x="570.0" y="1400.0"/>
      <vecteur use="extent" x="150.0" y="260.0"/>
    </plateform>
  </entities>
</map>

=== XenoAmess/ArenaShooter/project/data/mapXML/mapXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map SYSTEM "mapDTD.dtd" >
<map>
	<information>
		<spawn spawnperso="true" cooldown="2">
			<vecteur x="-700" y="-1" />
			<gun name="Minigun" weight="43"
				pathSprite="data/weapons/Minigun_1.png" soundPickup="GunCock_02"
				cooldown="0.03" uses="350" animPath="" warmupDuration="0.25"
				soundWarmup="warmup_minigun_01"
				bangSound="Bang1"
				noAmmoSound="no_ammo_01" bulletType="0"
				bulletSpeed="35" damage="1" cannonLength="2" recoil="0.2"
				thrust="2.75" size="64" proba="1">

				<vecteur use="handPosL" x="-2.5" y=".6" />
				<vecteur use="handPosR" x=".3" y=".3" />
			</gun>
			<gun name="assault" weight="43"
				pathSprite="data/weapons/Assaut_1.png" soundPickup="GunCock_01"
				cooldown="0.09" uses="100" animPath="" warmupDuration="0"
				soundWarmup=""
				bangSound="bang_tommy_gun_01"
				noAmmoSound="no_ammo_01" bulletType="0"
				bulletSpeed="35" damage="1" cannonLength=".58" recoil="1.6"
				thrust="2.00" size="64" proba="1">

				<vecteur use="handPosL" x="-2.5" y=".8" />
				<vecteur use="handPosR" x=".3" y=".4" />
			</gun>
			<gun name="ion" weight="50"
				pathSprite="data/weapons/RayGun1_tr.png" soundPickup="GunCock_03"
				cooldown="0.12" uses="100" animPath="" warmupDuration="0.8"
				soundWarmup="IonCharge3"
				bangSound="BangIonGun"
				noAmmoSound="no_ammo_01" bulletType="1"
				bulletSpeed="30" damage="1" cannonLength=".5" recoil="1"
				thrust="2.00" size="64" proba="1">

				<vecteur use="handPosL" x="-2.5" y=".6" />
				<vecteur use="handPosR" x=".3" y=".1" />
			</gun>
			<shotgun name="shotgun" weight="100"
				pathSprite="data/weapons/shotgun1.png" soundPickup="GunCock_02"
				cooldown="1.2" uses="6" animPath="" warmupDuration="0"
				soundWarmup=""
				bangSound="bang_shotgun_01"
				noAmmoSound="no_ammo_01" multiShot="25" dispersion="0.3" bulletType="0"
				bulletSpeed="32" damage="2" cannonLength=".6" recoil="2"
				thrust="25.00" size="2"  proba="1">

				<vecteur use="handPosL" x="1.5" y="0" />
				<vecteur use="handPosR" x=".5" y="0" />
			</shotgun>
			<entities>
				<mesh src="data/meshes/item_pickup/weapon_pickup.obj">
					<vecteur use="position" x="0" y="1" z="0" />
					<vecteur use="rotation" x="0" y="0" z="0" w="1" />
					<vecteur use="scale" x=".35" y=".35" z=".35" />
				</mesh>
			</entities>
		</spawn>
		
		<spawn spawnperso="true" cooldown="2">
			<vecteur x="7.0" y="-1" />
			<gun name="Minigun" weight="43"
				pathSprite="data/weapons/Minigun_1.png" soundPickup="GunCock_02"
				cooldown="0.03" uses="350" animPath="" warmupDuration="0.25"
				soundWarmup="warmup_minigun_01"
				bangSound="Bang1"
				noAmmoSound="no_ammo_01" bulletType="0"
				bulletSpeed="35" damage="1" cannonLength="1" recoil="0.2"
				thrust="2.75" size="64" proba="1">

				<vecteur use="handPosL" x="-2.5" y=".6" />
				<vecteur use="handPosR" x=".3" y=".3" />
			</gun>
			<gun name="assault" weight="43"
				pathSprite="data/weapons/Assaut_1.png" soundPickup="GunCock_01"
				cooldown="0.09" uses="100" animPath="" warmupDuration="0"
				soundWarmup=""
				bangSound="bang_tommy_gun_01"
				noAmmoSound="no_ammo_01" bulletType="0"
				bulletSpeed="35" damage="1" cannonLength=".58" recoil="1.6"
				thrust="2.00" size="64" proba="1">

				<vecteur use="handPosL" x="-2.5" y=".8" />
				<vecteur use="handPosR" x=".3" y=".4" />
			</gun>
			<gun name="ion" weight="50"
				pathSprite="data/weapons/RayGun1_tr.png" soundPickup="GunCock_03"
				cooldown="0.12" uses="100" animPath="" warmupDuration="0.8"
				soundWarmup="IonCharge3"
				bangSound="BangIonGun"
				noAmmoSound="no_ammo_01" bulletType="1"
				bulletSpeed="30" damage="1" cannonLength=".5" recoil="1"
				thrust="2.00" size="64" proba="1">

				<vecteur use="handPosL" x="-2.5" y=".6" />
				<vecteur use="handPosR" x=".3" y=".3" />
			</gun>
			<shotgun name="shotgun" weight="100"
				pathSprite="data/weapons/shotgun1.png" soundPickup="GunCock_02"
				cooldown="1.2" uses="6" animPath="" warmupDuration="0"
				soundWarmup=""
				bangSound="bang_shotgun_01"
				noAmmoSound="no_ammo_01" multiShot="25" dispersion="0.3" bulletType="0"
				bulletSpeed="32" damage="3" cannonLength=".6" recoil="2"
				thrust="25.00" size="2"  proba="1">

				<vecteur use="handPosL" x="1.5" y="0" />
				<vecteur use="handPosR" x=".5" y="0" />
			</shotgun>
			<melee name="kata" weight="5"
				pathSprite="data/weapons/sword_01.png" soundPickup="sword_draw_01"
				cooldown="0.12" uses="350" animPath="" warmupDuration="0.1"
				soundWarmup="" damage="3"
				bangSound="woosh_01" size="2" proba="1">
				
				<vecteur use="handPosL" x="-50" y="0" />
				<vecteur use="handPosR" x="0" y="0" />
			</melee>
			<entities>
				<mesh src="data/meshes/item_pickup/weapon_pickup.obj">
					<vecteur use="position" x="0" y="1" z="0" />
					<vecteur use="rotation" x="0" y="0" z="0" w="1" />
					<vecteur use="scale" x=".35" y=".35" z=".35" />
				</mesh>
			</entities>
		</spawn>

		<gravity>
			<vecteur x="0" y="9.807" />
		</gravity>

		<cameraBound w="100" x="-500" y="-100" z="500" />

		<sky>
			<vecteur x="0.659" y="0.835" z="0.996" use="bottom" />
			<vecteur x="0.016" y="0.145" z="0.565" use="top" />
		</sky>
	</information>

	<entities>
		<plateform>
			<vecteur x="0" y="12" use="position" />
			<vecteur x="75" y="10" use="extent" />
		</plateform>
		
		<plateform>
			<vecteur x="125" y="-5" use="position" />
			<vecteur x="50" y="3" use="extent" />
		</plateform>
		
		<plateform>
			<vecteur x="-125" y="-5" use="position" />
			<vecteur x="50" y="3" use="extent" />
		</plateform>

		<mesh src="data/meshes/windmills/Windmill_01_Static.obj">
			<vecteur use="position" x="22500" y="28000" z="-62500" />
			<vecteur use="rotation" x="0" y=".2" z="0" w="1" />
			<vecteur use="scale" x="95" y="95" z="95" />
			<entities>
				<mesh src="data/meshes/windmills/Windmill_01_Blades.obj">
					<!-- <vecteur use="position" x="-300" y="1200" z="0" /> -->
					<vecteur use="position" x="21200" y="13500" z="-61500" />
					<vecteur use="rotation" x="0" y=".2" z="0" w="1" />
					<vecteur use="scale" x="95" y="95" z="95" />
				</mesh>
			</entities>
		</mesh>

		<mesh src="data/meshes/landscape_field/Hill.obj">
			<vecteur use="position" x="0" y="53500" z="-22000" />
			<vecteur use="rotation" x="-0.2" y="0" z="0" w="1" />
			<vecteur use="scale" x="30" y="30" z="30" />
		</mesh>

	</entities>
</map>

=== XenoAmess/ArenaShooter/project/data/mapXML/AAHH.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map SYSTEM "mapDTD.dtd" >
<map name="A">
  <information>
    <spawn>
      <vecteur x="1945.0" y="1140.0"/>
    </spawn>
    <spawn>
      <vecteur x="1635.0" y="1520.0"/>
    </spawn>
    <spawn>
      <vecteur x="1475.0" y="1405.0"/>
    </spawn>
    <spawn>
      <vecteur x="1685.0" y="1215.0"/>
    </spawn>
    <spawn>
      <vecteur x="1725.0" y="790.0"/>
    </spawn>
    <spawn>
      <vecteur x="1615.0" y="1075.0"/>
    </spawn>
    <spawn>
      <vecteur x="1330.0" y="895.0"/>
    </spawn>
    <spawn>
      <vecteur x="1070.0" y="740.0"/>
    </spawn>
    <spawn>
      <vecteur x="1970.0" y="670.0"/>
    </spawn>
    <spawn>
      <vecteur x="565.0" y="440.0"/>
    </spawn>
    <spawn>
      <vecteur x="2745.0" y="740.0"/>
    </spawn>
    <gravity>
      <vecteur x="0.0" y="9.807"/>
    </gravity>
    <cameraBound w="1000" x="-5000" y="-1000" z="5000"/>
    <sky>
      <vecteur use="top" x="1.0" y="1.0" z="1.0"/>
      <vecteur use="bottom" x="1.0" y="1.0" z="1.0"/>
    </sky>
  </information>
  <entities>
    <plateform name="Platform_50613537244683">
      <vecteur use="position" x="550.0" y="900.0"/>
      <vecteur use="extent" x="150.0" y="10.0"/>
    </plateform>
    <plateform name="Platform_50645826099033">
      <vecteur use="position" x="2310.0" y="1980.0"/>
      <vecteur use="extent" x="150.0" y="1000.0"/>
    </plateform>
    <plateform name="Platform_50647460173982">
      <vecteur use="position" x="405.0" y="700.0"/>
      <vecteur use="extent" x="5.0" y="200.0"/>
    </plateform>
    <plateform name="Platform_50609146157398">
      <vecteur use="position" x="670.0" y="920.0"/>
      <vecteur use="extent" x="150.0" y="10.0"/>
    </plateform>
    <plateform name="Platform_50573622582054">
      <vecteur use="position" x="2030.0" y="2970.0"/>
      <vecteur use="extent" x="150.0" y="10.0"/>
    </plateform>
    <plateform name="Platform_2">
      <vecteur use="position" x="790.0" y="940.0"/>
      <vecteur use="extent" x="150.0" y="10.0"/>
    </plateform>
    <plateform name="Platform_50774568782919">
      <vecteur use="position" x="1085.0" y="1490.0"/>
      <vecteur use="extent" x="150.0" y="10.0"/>
    </plateform>
    <plateform name="Platform_1">
      <vecteur use="position" x="790.0" y="1950.0"/>
      <vecteur use="extent" x="150.0" y="1000.0"/>
    </plateform>
    <plateform name="Platform_50605705312757">
      <vecteur use="position" x="2500.0" y="980.0"/>
      <vecteur use="extent" x="500.0" y="10.0"/>
    </plateform>
    <plateform name="Platform_50788432437081">
      <vecteur use="position" x="1190.0" y="2570.0"/>
      <vecteur use="extent" x="250.0" y="10.0"/>
    </plateform>
    <plateform name="Platform_50777083426259">
      <vecteur use="position" x="2020.0" y="1920.0"/>
      <vecteur use="extent" x="150.0" y="10.0"/>
    </plateform>
    <plateform name="Platform_50611129024946">
      <vecteur use="position" x="550.0" y="570.0"/>
      <vecteur use="extent" x="150.0" y="10.0"/>
    </plateform>
    <plateform name="Platform_50782972109320">
      <vecteur use="position" x="1045.0" y="2200.0"/>
      <vecteur use="extent" x="150.0" y="10.0"/>
    </plateform>
  </entities>
</map>

=== XenoAmess/ArenaShooter/project/data/mapXML/tonneau.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE map SYSTEM "mapDTD.dtd">
<map>
  <information>
    <spawn cooldown="4" spawnperso="true">
      <vecteur x="245.0" y="160.0"/>
      			<gun name="Minigun" weight="43"
				pathSprite="data/weapons/Minigun_1.png" soundPickup="Bang1"
				fireRate="125" uses="350" animPath="" warmupDuration="15"
				soundWarmup="IonCharge1"
				bangSound="Bang1"
				noAmmoSound="GunCock1" bulletType="1"
				bulletSpeed="7.9" damage="1" cannonLength="10" recoil="12"
				thrust="22" size="32" proba="1">

				<vecteur use="handPosL" x="0" y="0" />
				<vecteur use="handPosR" x="0" y="0" />
			</gun>
			<entities>
				<mesh src="data/meshes/item_pickup/weapon_pickup.obj">
					<vecteur use="position" x="0" y="40" z="0" />
					<vecteur use="rotation" x="0" y="0" z="0" w="1" />
					<vecteur use="scale" x="35" y="35" z="35" />
				</mesh>
				</entities>
      
    </spawn>
    <spawn cooldown="4" spawnperso="true">
      <vecteur x="395.0" y="160.0"/>
   		<!-- <melee name="sword" soundWarmup="IonCharge1" animPath="" proba="1" uses="100" weight="7" warmupDuration="2" pathSprite="data/weapons/kata.png" damage="33" fireRate="3" soundPickup="Bang1" size="25" bangSound="Bang1">
   		</melee> -->
    </spawn>
    <spawn cooldown="4" spawnperso="true">
      <vecteur x="345.0" y="160.0"/>
    	<gun name="Minigun2" weight="43"
				pathSprite="data/weapons/Minigun_1.png" soundPickup="Bang1"
				fireRate="125" uses="350" animPath="" warmupDuration="15"
				soundWarmup="IonCharge1"
				bangSound="Bang1"
				noAmmoSound="GunCock1" bulletType="1"
				bulletSpeed="7.9" damage="1" cannonLength="10" recoil="12"
				thrust="22" size="32" proba="1">

				<vecteur use="handPosL" x="0" y="0" />
				<vecteur use="handPosR" x="0" y="0" />
			</gun>
    
    	<gun name="Alien" weight="125"
				pathSprite="data/weapons/alien.png" soundPickup="Bang1"
				fireRate="55" uses="52" animPath="" warmupDuration="5"
				soundWarmup="IonCharge1"
				bangSound="Bang1"
				noAmmoSound="GunCock1" bulletType="2"
				bulletSpeed="35.0" damage="27" cannonLength="10" recoil="7"
				thrust="22" size="32" proba="2">

				<vecteur use="handPosL" x="0" y="0" />
				<vecteur use="handPosR" x="0" y="0" />
			</gun>
    		<entities>
				<mesh src="data/meshes/item_pickup/weapon_pickup.obj">
					<vecteur use="position" x="0" y="0" z="0" />
					<vecteur use="rotation" x="0" y="0" z="0" w="1" />
					<vecteur use="scale" x="35" y="35" z="35" />
				</mesh>
				</entities>
    
    
    
    </spawn>
    <spawn cooldown="4" spawnperso="true">
      <vecteur x="295.0" y="160.0"/>
    </spawn>
    <spawn cooldown="4" spawnperso="true">
      <vecteur x="445.0" y="160.0"/>
    </spawn>
    <spawn cooldown="4" spawnperso="true">
      <vecteur x="265.0" y="439.0"/>
    </spawn>
    <spawn cooldown="4" spawnperso="true">
      <vecteur x="205.0" y="440.0"/>
    </spawn>
    <spawn cooldown="4" spawnperso="true">
      <vecteur x="325.0" y="440.0"/>
    </spawn>
    <spawn cooldown="4" spawnperso="true">
      <vecteur x="695.0" y="330.0"/>
    </spawn>
    <spawn cooldown="4" spawnperso="true">
      <vecteur x="645.0" y="330.0"/>
    </spawn>
    <spawn cooldown="4" spawnperso="true">
      <vecteur x="745.0" y="330.0"/>
    </spawn>
    <spawn cooldown="4" spawnperso="true">
      <vecteur x="145.0" y="440.0"/>
    </spawn>
    <gravity>
      <vecteur x="0.0" y="9.807"/>
    </gravity>
    <cameraBound w="1000" x="-5000" y="-1000" z="5000"/>
    <sky>
      <vecteur use="top" x="1.0" y="1.0" z="1.0"/>
      <vecteur use="bottom" x="1.0" y="1.0" z="1.0"/>
    </sky>
  </information>
  <entities>
       <plateform name="Platform_5404481793333">
      <vecteur use="position" x="405.0" y="750.0"/>
      <vecteur use="extent" x="500.0" y="10.0"/>
    </plateform>
    <plateform name="Platform_5391209996000">
      <vecteur use="position" x="350.0" y="260.0"/>
      <vecteur use="extent" x="150.0" y="10.0"/>
    </plateform>
    <plateform name="Platform_5398076260888">
      <vecteur use="position" x="695.0" y="441.0"/>
      <vecteur use="extent" x="150.0" y="10.0"/>
    </plateform>
    <plateform name="Platform_5400633540888">
      <vecteur use="position" x="146.0" y="563.0"/>
      <vecteur use="extent" x="150.0" y="10.0"/>
    </plateform>
    
   <mesh src="data/meshes/decor/tonneau.obj">
					<!-- <vecteur use="position" x="-300" y="1200" z="0" /> -->
					<vecteur use="position" x="200" y="40" z="0" />
					<vecteur use="rotation" x="0" y="0" z="0" w="1" />
					<vecteur use="scale" x="35" y="35" z="35" />
				</mesh>
				
   	<mesh src="data/meshes/decor/ammadetonneau.obj">
					<!-- <vecteur use="position" x="-300" y="1200" z="0" /> -->
					<vecteur use="position" x="320" y="40" z="20" />
					<vecteur use="rotation" x="0" y="0" z="0" w="1" />
					<vecteur use="scale" x="35" y="35" z="35" />
					</mesh>
		
  </entities>
</map>

=== XenoAmess/ArenaShooter/project/data/mapXML/menu_character_chooser.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map SYSTEM "mapDTD.dtd" >
<map>
	<information>
		<spawn cooldown="1">
			<vecteur x="0" y="0" />
		</spawn>

		<gravity>
			<vecteur x="0" y="9.807" />
		</gravity>

		<cameraPos x="0" y="0" z="8" />
		<cameraBound w="1000" x="-5000" y="-1000" z="5000" />

		<sky>
			<vecteur x="0.996" y="0.9098" z="0.003922" use="bottom" />
			<vecteur x="0.34901960784" y="0.13725490196" z="0.48235294118" use="top" />
		</sky>
	</information>

	<entities>
	</entities>
</map>

=== XenoAmess/ArenaShooter/project/data/mapXML/menu_empty.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map SYSTEM "mapDTD.dtd" >
<map>
	<information>
		<spawn cooldown="1">
			<vecteur x="0" y="0" />
		</spawn>

		<gravity>
			<vecteur x="0" y="9.807" />
		</gravity>

		<cameraBound w="1000" x="-5000" y="-1000" z="5000" />

		<sky>
			<vecteur x="0" y="0" z="0" use="bottom" />
			<vecteur x="0" y="0" z="0" use="top" />
		</sky>
	</information>

	<entities>
	</entities>
</map>
